[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn =  { version = "2.0.111", features = ["extra-traits", "full"] }
quote = "1.0.42"
proc-macro2 = "1.0.103"
